# Generated by Django 3.2.6 on 2021-08-31 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('rut', models.CharField(max_length=10)),
                ('correo', models.EmailField(max_length=254)),
                ('celular', models.CharField(max_length=10)),
                ('direccion', models.TextField()),
                ('region', models.CharField(max_length=15)),
                ('comuna', models.CharField(max_length=15)),
                ('idCliente', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('sexo', models.CharField(max_length=10)),
                ('raza', models.CharField(max_length=10)),
                ('fechaNacimiento', models.DateField()),
                ('numeroMicroChip', models.IntegerField()),
                ('veterinaria', models.CharField(max_length=20)),
                ('direccion', models.TextField()),
                ('propietario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mascotas.cliente')),
            ],
        ),
    ]
