# Generated by Django 3.2.6 on 2021-08-31 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mascotas', '0002_mascota_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContratarPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoPlan', models.CharField(max_length=10)),
                ('fechaContrato', models.DateField()),
                ('nombre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mascotas.cliente')),
                ('nombreMascota', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mascotas.mascota')),
            ],
        ),
    ]
