# Generated by Django 3.2.6 on 2021-08-31 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mascotas', '0003_contratarplan'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contratarplan',
            old_name='nombre',
            new_name='nombreCliente',
        ),
    ]
