# Generated by Django 3.2.6 on 2021-09-03 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascotas', '0007_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='direccion',
            field=models.CharField(max_length=250),
        ),
    ]
